# Ejercicio 3: Modelo Vectorial y TF-IDF

## Objetivo de la práctica

- Comprender el modelo vectorial como base para representar documentos y consultas.
- Calcular la matriz TF-IDF para el corpus `data/01_corpus_turismo_500.txt`
- Calcular la matriz TF-IDF para el corpus `Gutenberg 1000`

### Paso 1: Calcular la matriz TF-IDF para el corpus `data/01_corpus_turismo_500.txt`

Primero obtenemos el corpus del archivo .txt

In [ ]:
import os
path = "C:\\Users\\mark_\\Documents\\ir26a\\03tfidf\\data"
file = os.listdir(path)

contenido = []

with open(os.path.join(path, file[0]),"r", encoding="utf-8") as f:
    contenido = f.read()
    palabras = set(contenido.split())

print(list(palabras)[:100])

['deslumbra', 'deportes', 'Vilcabamba', 'visitan', 'Guayaquil', 'senderismo.', 'tranquilo', 'megadiverso,', 'longevidad', 'Malecón', 'nocturna', 'local', 'artesanía', 'lagunas', 'en', 'indígena', 'típica', 'destaca', 'Islas', 'rafting.', 'sorprende', 'Agua', 'lugar', 'país', 'naturaleza', 'tiene', 'histórico', 'los', 'Las', 'Cajas', 'atrae', 'Santa', 'Cuenca', 'popular', 'Parque', 'su', 'atraen', 'próximo', 'turquesa', 'surfistas', 'destino', 'Amazonía', 'conecta', 'Ecuador', 'a', 'experiencia', 'Durante', 'invita', 'sorprendente', 'Un', 'Mindo', 'gastronomía', 'Galápagos', 'playas', 'auténtico', 'Los', 'canopy.', 'con', 'turismo', 'El', 'Montañita', 'Humanidad', 'conocido', 'feriado,', 'caminatas', 'se', 'Laguna', 'durante', 'avistamiento', 'vida', 'Baños', 'visitantes', 'las', 'volcán', 'Perfecto', 'Otavalo', 'visitar.', 'arquitectura', 'surf.', 'es', 'interesados', 'mercado', 'Quilotoa', 'del', 'Spondylus', 'Ideal', 'para', 'biodiversidad', 'aves', 'de', 'como', 'Quito', 'ecuatoriana', 'por', 'única', 'el', 'aventura', 'llena', 'feriados', 'Una']

Luego procedemos a calcular los valores de frecuencia con que aparece cada término dentro del documento. Para ello hacemos uso del concepto de índice invertido.

In [20]:
import pandas as pd

indice_invertido = {}

for palabra in palabras:
    indice_invertido[palabra] = 1

for palabra in contenido.split(): 
    if palabra in indice_invertido.keys():
        indice_invertido[palabra] += 1
    
t1 = pd.DataFrame(list(indice_invertido.items()), columns=["palabra", "frecuencia"])
t1.head(20)

         palabra  frecuencia
0      deslumbra          35
1       deportes          33
2     Vilcabamba          28
3        visitan          28
4      Guayaquil          34
5    senderismo.          18
6      tranquilo          17
7   megadiverso,          37
8     longevidad          28
9        Malecón          34
10      nocturna          34
11         local          33
12     artesanía          34
13       lagunas          38
14            en          28
15      indígena          34
16        típica          33
17       destaca          33
18         Islas          34
19      rafting.          23

Con estas frecuencias calculamos el valor de tf.

In [21]:
import math
tf = {}
for palabra, frec in indice_invertido.items():
    tf[palabra] = 1 + math.log10(frec)

Tabla_tf = pd.DataFrame(list(tf.items()), columns=["palabra", "tf"])
Tabla_tf.head(20)

         palabra        tf
0      deslumbra  2.544068
1       deportes  2.518514
2     Vilcabamba  2.447158
3        visitan  2.447158
4      Guayaquil  2.531479
5    senderismo.  2.255273
6      tranquilo  2.230449
7   megadiverso,  2.568202
8     longevidad  2.447158
9        Malecón  2.531479
10      nocturna  2.531479
11         local  2.518514
12     artesanía  2.531479
13       lagunas  2.579784
14            en  2.447158
15      indígena  2.531479
16        típica  2.518514
17       destaca  2.518514
18         Islas  2.531479
19      rafting.  2.361728

Con el valor de tf ya calculado, procedemos a calcular el valor de idf. Para este primer caso, hay que considerar el número total de términos y la frecuencia con que aparecen dentro del documento. Esto debido a que estamos evaluando un solo libro, caso contrario tendríamos un valor de cero para el idf indicando que el término no es muy informativo al compararlo en un solo libro.

In [ ]:
N = len(contenido.split())
idf = {}
for palabra, frec in indice_invertido.items():
    df_t = frec
    idf[palabra] = math.log10(N/df_t)
    
Tabla_idf = pd.DataFrame(list(idf.items()), columns=["palabra", "idf"])
Tabla_idf.head(20)

6111 129

         palabra       idf
0      deslumbra  2.242044
1       deportes  2.267598
2     Vilcabamba  2.338954
3        visitan  2.338954
4      Guayaquil  2.254633
5    senderismo.  2.530840
6      tranquilo  2.555663
7   megadiverso,  2.217911
8     longevidad  2.338954
9        Malecón  2.254633
10      nocturna  2.254633
11         local  2.267598
12     artesanía  2.254633
13       lagunas  2.206329
14            en  2.338954
15      indígena  2.254633
16        típica  2.267598
17       destaca  2.267598
18         Islas  2.254633
19      rafting.  2.424384

Creamos la matriz TF-IDF para este único libro.

In [29]:
TF_IDF = {}
for palabra in palabras:
    TF_IDF[palabra] = tf[palabra] * idf[palabra]

Tabla_TF_IDF = pd.DataFrame(list(TF_IDF.items()), columns=["palabra", "TF-IDF"])
Tabla_TF_IDF.head(20)

         palabra    TF-IDF
0      deslumbra  5.703913
1       deportes  5.710978
2     Vilcabamba  5.723791
3        visitan  5.723791
4      Guayaquil  5.707557
5    senderismo.  5.707733
6      tranquilo  5.700277
7   megadiverso,  5.696042
8     longevidad  5.723791
9        Malecón  5.707557
10      nocturna  5.707557
11         local  5.710978
12     artesanía  5.707557
13       lagunas  5.691851
14            en  5.723791
15      indígena  5.707557
16        típica  5.710978
17       destaca  5.710978
18         Islas  5.707557
19      rafting.  5.725736

### Paso 2: Construir el corpus `Gutenberg 1000`

El corpus `Gutenberg 1000` es un corpus compuesto por 1000 libros de Gutenberg Project

In [87]:

import re


path2 = "C:\\Users\\mark_\\Documents\\ir26a\\Data\\Gutenberg_1000"
files = os.listdir(path2)
contenido_libros = {}
indice_invertido = {}
for file in files:
    # Se iteran los archivos
    with open(path2 + "\\" + file, "r", encoding="utf-8") as f:
        contenido = f.read().lower()
        # Extrae solo palabras (letras y números)
        palabras = re.findall(r'\w+', contenido)
        contenido_libros[file] = contenido
        vocabulario = set(palabras)
        for palabra in vocabulario:
            if palabra in indice_invertido:
                indice_invertido[palabra].append(file)
            else:
                indice_invertido[palabra] = [file]
print('Número de palabras del índice invertido: ',len(indice_invertido))

Número de palabras del índice invertido:  1061431

In [64]:
Tabla_archivos = pd.DataFrame(list(indice_invertido.items()), columns=['Palabra', 'Archivos'])
Tabla_archivos.head(20)

       Palabra                                           Archivos
0       moritz  [Book1.txt, book11839.txt, book21349.txt, book...
1        naval  [Book1.txt, book10008.txt, book10077.txt, book...
2   passionate  [Book1.txt, book10.txt, book100.txt, book10339...
3         nook  [Book1.txt, book10077.txt, book10392.txt, book...
4     vehement  [Book1.txt, book10.txt, book10372.txt, book105...
5       cooped  [Book1.txt, book10.txt, book11120.txt, book120...
6      amongst  [Book1.txt, book10.txt, book100.txt, book10058...
7       deeper  [Book1.txt, book10.txt, book100.txt, book10008...
8     reproach  [Book1.txt, book10.txt, book100.txt, book10008...
9       pardon  [Book1.txt, book10.txt, book100.txt, book10008...
10      become  [Book1.txt, book10.txt, book100.txt, book10008...
11       times  [Book1.txt, book10.txt, book100.txt, book10008...
12         men  [Book1.txt, book10.txt, book100.txt, book10008...
13     eastern  [Book1.txt, book10.txt, book10008.txt, book100...
14        vast  [Book1.txt, book10.txt, book100.txt, book10008...
15    vigorous  [Book1.txt, book10.txt, book100.txt, book10077...
16  previously  [Book1.txt, book10.txt, book100.txt, book10008...
17      arisen  [Book1.txt, book10.txt, book10058.txt, book100...
18  suffocated  [Book1.txt, book1068.txt, book10974.txt, book1...
19     founded  [Book1.txt, book10.txt, book100.txt, book10058...

### Paso 3: Calcular la matriz TF-IDF para el corpus `Gutenberg 1000`

Creamos la función buscar para encontrar facilmente en que libros se encuentra, y con ese dato calculamos las frecuencias con que aparece cada palabra en cada libro.

In [92]:
from collections import Counter

def buscar_palabra(palabra, texto):
   palabras = re.findall(r'\w+', texto.lower())
   contador = Counter(palabras)
   return contador[palabra]

In [99]:
def contar_palabra(palabra):
    frec_por_libro = {}
    archivos = indice_invertido.get(palabra, [])
    for archivo in archivos:
        frec_por_libro[archivo] = 0
        cantidad = re.findall(r'\w+', contenido_libros[archivo].lower()).count(palabra)
        frec_por_libro[archivo] = cantidad
    return frec_por_libro

Verificamos que nuestras funciones sean válidas para una palabra.

In [100]:
palabra = "creator"
print(contar_palabra(palabra))

{'Book1.txt': 20, 'book10.txt': 24, 'book10058.txt': 7, 'book10339.txt': 1, 'book10531.txt': 2, 'book10627.txt': 2, 'book11120.txt': 1, 'book11314.txt': 1, 'book11488.txt': 5, 'book118.txt': 1, 'book1197.txt': 3, 'book12101.txt': 3, 'book12144.txt': 2, 'book12193.txt': 1, 'book12238.txt': 1, 'book1239.txt': 1, 'book12463.txt': 1, 'book12484.txt': 1, 'book12563.txt': 3, 'book12618.txt': 1, 'book12843.txt': 2, 'book12930.txt': 2, 'book13.txt': 1, 'book13237.txt': 13, 'book13238.txt': 1, 'book13367.txt': 1, 'book1381.txt': 1, 'book14.txt': 2, 'book14501.txt': 1, 'book14551.txt': 6, 'book18947.txt': 3, 'book19269.txt': 2, 'book20696.txt': 1, 'book2145.txt': 2, 'book222.txt': 1, 'book23931.txt': 1, 'book2596.txt': 1, 'book26.txt': 1, 'book28.txt': 2, 'Book3.txt': 77, 'book30125.txt': 1, 'book30262.txt': 2, 'book30336.txt': 5, 'book30637.txt': 3, 'book30745.txt': 1, 'book32.txt': 1, 'book32730.txt': 1, 'book33.txt': 1, 'book33005.txt': 2, 'book34.txt': 5, 'book3437.txt': 6, 'book3444.txt': 7, 'book34520.txt': 30, 'book34716.txt': 10, 'book35813.txt': 5, 'book36.txt': 1, 'book3671.txt': 1, 'book37386.txt': 5, 'book39.txt': 2, 'book39196.txt': 6, 'book39458.txt': 6, 'book4077.txt': 1, 'book41271.txt': 1, 'book41492.txt': 2, 'book41704.txt': 1, 'book41708.txt': 1, 'book42.txt': 7, 'book42332.txt': 14, 'book42343.txt': 4, 'book42359.txt': 1, 'book42629.txt': 1, 'book42672.txt': 1, 'book42828.txt': 1, 'book43.txt': 1, 'book43049.txt': 1, 'book43300.txt': 1, 'book43738.txt': 4, 'book44.txt': 1, 'book44035.txt': 26, 'book44209.txt': 6, 'book44615.txt': 1, 'book45048.txt': 45, 'book45053.txt': 13, 'book45074.txt': 2, 'book45376.txt': 8, 'book45677.txt': 1, 'book46156.txt': 3, 'book46391.txt': 1, 'book46530.txt': 1, 'book46993.txt': 1, 'book47.txt': 21, 'book47316.txt': 9, 'book47462.txt': 1, 'book47864.txt': 31, 'book48010.txt': 1, 'book48170.txt': 1, 'book48818.txt': 1, 'book49003.txt': 1, 'book49035.txt': 1, 'book4917.txt': 1, 'book49282.txt': 1, 'book4986.txt': 1, 'book50021.txt': 4, 'book50167.txt': 2, 'book50454.txt': 2, 'book51003.txt': 1, 'book52059.txt': 1, 'book5249.txt': 1, 'book52534.txt': 3, 'book52564.txt': 6, 'book52622.txt': 1, 'book52639.txt': 1, 'book52642.txt': 1, 'book52734.txt': 1, 'book52845.txt': 1, 'book53.txt': 6, 'book5317.txt': 2, 'book53526.txt': 1, 'book53917.txt': 5, 'book53960.txt': 2, 'book54.txt': 3, 'book54036.txt': 10, 'book54345.txt': 2, 'book54705.txt': 1, 'book54736.txt': 4, 'book54757.txt': 3, 'book54910.txt': 1, 'book55060.txt': 1, 'book55331.txt': 3, 'book55396.txt': 2, 'book55540.txt': 2, 'book55819.txt': 2, 'book55986.txt': 2, 'book56090.txt': 3, 'book56227.txt': 2, 'book56480.txt': 2, 'book56571.txt': 2, 'book56667.txt': 2, 'book56865.txt': 3, 'book57050.txt': 1, 'book57091.txt': 1, 'book57110.txt': 1, 'book57192.txt': 2, 'book57359.txt': 4, 'book57379.txt': 1, 'book57512.txt': 1, 'book57763.txt': 1, 'book58062.txt': 42, 'book58102.txt': 1, 'book58152.txt': 1, 'book58186.txt': 5, 'book58386.txt': 1, 'book59413.txt': 1, 'book59530.txt': 2, 'book5959.txt': 4, 'book59955.txt': 2, 'book59962.txt': 1, 'Book6.txt': 1, 'book60178.txt': 2, 'book60200.txt': 1, 'book60212.txt': 1, 'book60751.txt': 1, 'book60783.txt': 1, 'book60866.txt': 1, 'book60915.txt': 6, 'book61.txt': 2, 'book64.txt': 6, 'book66.txt': 1, 'book6780.txt': 1, 'book69.txt': 7, 'book70.txt': 4, 'book71.txt': 4, 'book7178.txt': 3, 'book72.txt': 1, 'book73.txt': 36, 'book7658.txt': 6, 'book78.txt': 5, 'book79.txt': 3, 'book81.txt': 4, 'book83.txt': 2, 'book85.txt': 1, 'book86.txt': 2, 'book97.txt': 2, 'book989.txt': 1, 'book99.txt': 4}

Creamos nuestro diccionario de frecuencias de palabras por cada libro en el que aparece.

In [91]:
frecuencia_palabra = {}
for palabra in indice_invertido.keys():
    frecuencia_palabra[palabra] = contar_palabra(palabra)

# Tabla_frec = pd.DataFrame(list(frecuencia_palabra.items()), columns=['Palabra', 'Frecuencia'])
# Tabla_frec.head(20)

KeyboardInterrupt:

In [ ]:
N = len(files)
df_t_1000 = {}
for palabra, archivos in indice_invertido.items():
    df_t_1000[palabra] = len(archivos)

Tabla_frecuencia = pd.DataFrame(list(df_t_1000.items()), columns=['Palabra', 'Frecuencia'])
Tabla_frecuencia.head(20)

             Palabra  Frecuencia
0          creator,”           1
1          conflict.         104
2          retreats.          13
3              naval         169
4   shrine-dedicated           1
5         passionate         309
6           forward;         103
7               bed;         171
8               nook         113
9            mildly,          46
10            cooped          49
11          library.         126
12         helpless;          18
13           amongst         349
14       DISTRIBUTOR         381
15            deeper         454
16       profoundly.          34
17           Neither         455
18             upon.         309
19          reproach         243

### Paso 4: Programar una función `buscar()` para el corpus `Gutenberg 1000`